blank_issues_enabled: false
contact_links:
  - name: è³ªå•ãƒ»ç›¸è«‡
    url: https://github.com/habitat-lab/board-game-prototype/discussions
    about: ãƒã‚°å ±å‘Šã‚„æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆä»¥å¤–ã®è³ªå•ãƒ»ç›¸è«‡ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„ã€‚

# ãƒ†ãƒ•ã‚©ãƒ«ãƒˆãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ
default_template: "feature_request.yml"

# ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆã®ä¸¦ã³é †ã‚„è¡¨ç¤ºè¨­å®š
defaults:
  - template: "bug_report.yml"
    name: "ğŸ› ãƒã‚°å ±å‘Š"
    about: "ãƒã‚°ã‚’å ±å‘Šã™ã‚‹"
  - template: "feature_request.yml"
    name: "ğŸ’¡ æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆ"
    about: "æ–°æ©Ÿèƒ½ã®ã‚¢ã‚¤ãƒ‡ã‚¢ã‚’ææ¡ˆã™ã‚‹"
